language: python
python: 2.7
cache:
 directories:
  - $HOME/miniconda3


env:
  - TEST=tools/msPurity/combineAnnotations.xml


before_install:
 - pip install --upgrade pip setuptools
 - pip install planemo
 
 
script:
- planemo lint ${TRAVIS_BUILD_DIR}/${TEST}
- planemo test  --conda_debug  ${TRAVIS_BUILD_DIR}/${TEST}

