{% set version="1.4.1" %}
{% set name="msPurity" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'

source:
  fn: 33fe897a38e0e062cf6f47103dd5d9dddefbb9f3.zip
  url: https://github.com/Viant-Metabolomics/msPurity/archive/33fe897a38e0e062cf6f47103dd5d9dddefbb9f3.zip


build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=3.4.1'
    - bioconductor-mzr
    - bioconductor-xcms
    - r-optparse
    - r-dbi
    - r-dosnow
    - r-fastcluster
    - r-foreach
    - r-ggplot2
    - r-plyr
    - r-rcpp
    - r-reshape2
    - r-rsqlite
    - r-stringr
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - 'r-base >=3.4.1'
    - bioconductor-mzr
    - bioconductor-xcms
    - r-optparse
    - r-dbi
    - r-dosnow
    - r-fastcluster
    - r-foreach
    - r-ggplot2
    - r-plyr
    - r-rcpp
    - r-reshape2
    - r-rsqlite
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Assess the contribution of the targeted precursor in fragmentation acquired or anticipated isolation windows using a metric called "precursor purity". Also provides simple processing steps (averaging, filtering, blank subtraction, etc) for DI-MS data. Works for both LC-MS(/MS) and DI-MS(/MS) data. Spectral matching of fragmentation spectra can also be run against a SQLite database of library spectra.'
