owner: tomnl
remote_repository_url: https://github.com/computational-metabolomics/mspurity-galaxy
homepage_url:  https://github.com/computational-metabolomics/mspurity-galaxy
categories: ["Metabolomics"]
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the mspurity_package"
suite:
  name: "suite_mspurity"
  description: "wrapper for msPurity R package"
  long_description: "Galaxy wrappers for msPurity R packages for precursor ion purity assessments and spectral matching"
  type: repository_suite_definition