categories: ["Metabolomics"]
homepage_url:  https://github.com/computational-metabolomics/mspurity-galaxy
long_description: |
  Galaxy wrappers for msPurity R packages for precursor ion purity assessments and spectral matching

  License: GPL Version 3 (or later).

  The msPurity package and the tool wrappers were originally writen by Thomas N Lawson
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the mspurity_package"
suite:
  name: suite_mspurity
  description: wrapper for msPurity R package
  type: repository_suite_definition
owner: tomnl
remote_repository_url: https://github.com/computational-metabolomics/mspurity-galaxy
type: unrestricted